zephyr: Fix incorrect cmake function used to include library
zephyrproject-rtos/tinycbor pull request #13
Opened 2020-03-09 09:49 UTC by de-nordic

Incorrect cmake function has been used to include TinyCBOR library,
as a result cmake has not been adding include paths, for the library
headers, into compilation.

Addresses issue:
https://github.com/zephyrproject-rtos/zephyr/issues/23324

Signed-off-by: Dominik Ermel <dominik.ermel@nordicsemi.no>

2020-03-18 14:48 UTC, nvlsianpu approved these changes

2020-03-18 16:31 UTC, nvlsianpu commented
cc @SebastianBoe

2020-03-19 08:41 UTC, SebastianBoe requested changes
This is a deliberate design decision. tincybor/include is added to the TINYCBOR interface library instead of the global include paths.

Any source file that needs to use TINYCBOR must be in a library that links with TINYCBOR. Like this:

```
zephyr_library()
zephyr_library_sources(some_file_that_uses_tinycbor.c)
zephyr_library_link_libraries(TINYCBOR)
```

2020-03-19 08:51 UTC, de-nordic commented
> 
> 
> This is a deliberate design decision. tincybor/include is added to the TINYCBOR interface library instead of the global include paths.

Would you like to block the change in such case? What is a rationale for adding TINYCBOR in such a way?

2020-03-19 09:00 UTC, SebastianBoe commented
The rationale is to minimize scope and thereby reduce aliasing issues.

e.g. if two files accidentally have the same include path, then interface libraries can be used to disambiguate.

```
tinycbor/include/utils.h
other_project/include/utils.h

user.c:
#include <utils.h>

```

Here, both paths could be used as include paths, but they could not both be added to the global include paths.

I can't say why the original author used an interface library instead of the global include paths. Maybe there exists an aliasing issue that he needed to resolve, or maybe he just copied the code cargo-cult style.

You may either remove the interface library and work directly on the global includes, or have the library that is missing it's include link with the TINYCBOR interface library.

But there is no point in having an interface library that is added to the global includes as we do here.

2020-03-19 09:01 UTC, SebastianBoe requested changes
Changes requested

2020-03-19 09:50 UTC, de-nordic commented
> 
> 
> The rationale is to minimize scope and thereby reduce aliasing issues.
> 
> e.g. if two files accidentally have the same include path, then interface libraries can be used to disambiguate.

I think this is already resolved by placing all header files for tinycbor in include/tinucbor, which, together with:
```
target_include_directories(TINYCBOR INTERFACE ../include)
```
line in CMakeList.txt makes it mandatory to include cbor headers prefixed  with tinycbor directory, e.g.:
```
#include <tinycbor/cbor.h>
```

> But there is no point in having an interface library that is added to the global includes as we do here.

How would you then recommend resolving this? I understand that now some of users think that when they turn on menuconfig option, that includes tinycbor, they are ready to go and all they have to do is to include cbor headers into source code, as the include paths be added for them to compiler cmd line.

2020-03-19 10:01 UTC, SebastianBoe commented
Then let us assume that disambiguating is not necessary.

I would recommend removing the TINYCBOR interface library and all references to it.

The tinycbor include path would then be added once like this:

zephyr_include_directories(../include)

2020-03-19 11:09 UTC, SebastianBoe approved these changes

2020-03-19 11:10 UTC, de-nordic commented
@SebastianBoe  Does the current approach follow  your advice correctly?

2020-03-19 11:14 UTC, SebastianBoe commented
Yes

2020-03-24 17:06 UTC, de-nordic commented
@carlescufi https://github.com/zephyrproject-rtos/zephyr/pull/23552 is green, we can start merging this set of PR

2020-03-24 18:12 UTC, carlescufi approved these changes

2020-03-24 18:12 UTC, merged

2020-03-25 10:32 UTC, nvlsianpu commented
@de-nordic I synchronized zephyr-rtos/mcuboot. Do we need to upgrade manifest?

2020-03-25 10:35 UTC, de-nordic commented
> 
> 
> @de-nordic I synchronized zephyr-rtos/mcuboot. Do we need to upgrade manifest?

Yes, this is done here: https://github.com/zephyrproject-rtos/zephyr/pull/23552